version: '3.3'
services:
    rabbitmq:
        container_name: rbmq-server
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        ports:
            - '8080:15672'
            - '5672:5672'
        image: 'rabbitmq:3-management'